apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: vuln-scanner

# List of resources to include
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/part-of: secure-devsecops-platform
  app.kubernetes.io/component: security-service
  app.kubernetes.io/managed-by: kustomize

# ConfigMap generator for additional configurations
configMapGenerator:
  - name: vuln-scanner-config-env
    behavior: merge
    literals:
      - SCAN_TIMEOUT=5m
      - LOG_LEVEL=info
      - TRIVY_NO_PROGRESS=true

# Secret generator for additional secrets
secretGenerator:
  - name: vuln-scanner-secrets
    behavior: merge
    type: Opaque
    envs:
      - .env.secrets # This file should be added to .gitignore

# Images customization
images:
  - name: ${ECR_REGISTRY}/vuln-scanner
    newName: ${ECR_REGISTRY}/vuln-scanner
    newTag: latest

# Patches to apply
patchesStrategicMerge:
  # - patches/increase-replica-count.yaml
  # - patches/set-memory-limit.yaml

# Vars for substitution
vars:
  - name: ECR_REGISTRY
    objref:
      kind: ConfigMap
      name: vuln-scanner-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ecr_registry
  - name: AWS_ACCOUNT_ID
    objref:
      kind: ConfigMap
      name: vuln-scanner-config
      apiVersion: v1
    fieldref:
      fieldpath: data.aws_account_id

# Configuration for applying resources
# This ensures that resources are applied in the correct order
configurations:
  - kustomizeconfig.yaml
