apiVersion: v1
kind: Secret
metadata:
  name: vuln-scanner-secrets
  namespace: vuln-scanner
  labels:
    app: vuln-scanner
    app.kubernetes.io/name: vuln-scanner
    app.kubernetes.io/part-of: secure-devsecops-platform
    app.kubernetes.io/component: security-service
type: Opaque
stringData:
  # In production, replace these with actual secrets using a secure method
  # such as Sealed Secrets, Vault, or CI/CD pipeline secret injection
  jwt_secret: "change-me-to-a-secure-random-string-in-production"
  api_key: "sample-api-key-replace-in-production"
  db_password: "sample-db-password-replace-in-production"
  webhook_secret: "sample-webhook-secret-replace-in-production"
  # AWS credentials should preferably use IRSA (IAM Roles for Service Accounts)
  # but included here as a fallback option
  aws_access_key_id: ""
  aws_secret_access_key: ""
