apiVersion: v1
kind: Service
metadata:
  name: vuln-scanner
  namespace: vuln-scanner
  labels:
    app: vuln-scanner
    app.kubernetes.io/name: vuln-scanner
    app.kubernetes.io/part-of: secure-devsecops-platform
    app.kubernetes.io/component: security-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vuln-scanner
